name: CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  lint:
    if: >-
      github.event_name == 'push' || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Push)
        if: github.event_name == 'push'
        uses: actions/checkout@v2.3.4

      - name: Checkout (Pull Request Target)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          # We are in a pull_request_target event - we need to explicitly checkout the PR's head.
          # Otherwise we would be running against main branch
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'

      - name: Restore node_modules
        uses: actions/cache@v2.1.5
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Restore .npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v2.1.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            ${{ runner.os }}-npm-cache-

      - run: npm config set @bit:registry https://node.bit.dev

      - name: Install dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - run: npm run lint:quiet

  prettier:
    if: >-
      github.event_name == 'push' || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Push)
        if: github.event_name == 'push'
        uses: actions/checkout@v2.3.4

      - name: Checkout (Pull Request Target)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          # We are in a pull_request_target event - we need to explicitly checkout the PR's head.
          # Otherwise we would be running against main branch
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'

      - name: Restore node_modules
        uses: actions/cache@v2.1.5
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Restore .npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v2.1.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            ${{ runner.os }}-npm-cache-

      - run: npm config set @bit:registry https://node.bit.dev

      - name: Install dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - run: npm run prettier:check

  test:
    if: >-
      github.event_name == 'push' || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Push)
        if: github.event_name == 'push'
        uses: actions/checkout@v2.3.4

      - name: Checkout (Pull Request Target)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          # We are in a pull_request_target event - we need to explicitly checkout the PR's head.
          # Otherwise we would be running against main branch
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'

      - name: Restore node_modules
        uses: actions/cache@v2.1.5
        id: node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Restore .npm cache
        if: steps.node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v2.1.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            - ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
            - ${{ runner.os }}-npm-cache-

      - run: npm config set @bit:registry https://node.bit.dev

      - name: Install dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: CYPRESS_INSTALL_BINARY=0 npm ci --prefer-offline --no-audit

      - run: |
          npm run test -- --ci --coverage --reporters=default --reporters=jest-junit
          npm run test:coverage
